<?php

namespace app\admin\controller;

use app\common\controller\BaseController;
use support\Request;

class Base extends BaseController
{
    function beforeAction(Request $request)
    {
        parent::beforeAction($request); // TODO: Change the autogenerated stub
        $this->assign('admin_info',$request->admin_info);
    }
}